//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasesTable
    {
        public int CasesID { get; set; }
        public System.DateTime cDate { get; set; }
        public int totalCases { get; set; }
        public int newCases { get; set; }
    }
}
