//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CovidPetsEntities2 : DbContext
    {
        public CovidPetsEntities2()
            : base("name=CovidPetsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BreedsTable> BreedsTables { get; set; }
        public virtual DbSet<CasesTable> CasesTables { get; set; }
        public virtual DbSet<PetsTable> PetsTables { get; set; }
        public virtual DbSet<SpeciesTable> SpeciesTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
